export interface IImprovementsJson {}
export enum WorkerEvents {
  FETCH_SITEMAP = "FETCH_SITEMAP",
  START_SEO_ANALYSIS = "START_SEO_ANALYSIS",
}
export enum SeoTechIssueType {
  SITEMAP = "SITEMAP",
  TITLE = "TITLE",
  META_TAG = "META_TAG",
  CANONICAL = "CANONICAL",
  STRUCTURED_DATA = "STRUCTURED_DATA",
  IMAGE_ALT_TEXT = "IMAGE_ALT_TEXT",
  H1_AND_ANCHOR_TEXT = "H1_AND_ANCHOR_TEXT",
  OG_IMAGE = "OG_IMAGE",
}
